export const endpoints = {
  login: `/v1/admin/auth/login`,
  me: `/v1/admin/auth/me`,
  profile: `/v1/admin/profile`,
  skills: `/v1/admin/skills`,
  experience: `/v1/admin/experience`,
  education: `/v1/admin/education`,
  services: `/v1/admin/services`,
  faqs: `/v1/admin/faqs`,
  projects: `/v1/admin/projects`,
  posts: `/v1/admin/posts`,
  testimonials: `/v1/admin/testimonials`,
  socials: `/v1/admin/socials`,
  settings: `/v1/admin/settings`,
  media: `/v1/admin/media`,
  messages: `/v1/admin/messages`,
  changePassword: `/v1/admin/auth/change-password`,
  changeEmail: `/v1/admin/auth/change-email`,
  forgotPassword: `/v1/admin/auth/forgot-password`,
  resetPassword: `/v1/admin/auth/reset-password`,
};
